inspire/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views as user_views
from projects import views as project_views
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('', include('users.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('api-token-auth/', obtain_auth_token)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from .views import ProfileList
 
urlpatterns = [
  path('profile/', views.profile, name='profile'),
  path('git', views.ProfileList.as_view()),
]

projects/models.py
import math
from django.db import models
from PIL import Image
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MaxValueValidator

class Project(models.Model):
  publisher = models.ForeignKey(User, on_delete=models.CASCADE)
  tag = models.CharField(max_length=50, blank=True, null=True)
  title = models.CharField(max_length=100)
  description = models.CharField(max_length=250)
  image = CloudinaryField('image')
  link = models.URLField(max_length=200)
  country = models.CharField(max_length=100)
  created_at = models.DateField(auto_now_add=True)
  updated_at = models.DateField(auto_now=True)

  def __str__(self):
    return self.title

  def save_project(self):
    return self.save()

  @classmethod
  def get_project(cls, pk):
    project = cls.objects.get(id=pk)
    return project

  def get_absolute_url(self):
    return reverse('post-detail', kwargs={'pk': self.pk})


class Rating(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  project = models.ForeignKey(Project, on_delete=models.CASCADE)
  design = models.PositiveIntegerField(default=0,validators=[MaxValueValidator(10)])
  content = models.PositiveIntegerField(default=0,validators=[MaxValueValidator(10)])
  usability = models.PositiveIntegerField(default=0,validators=[MaxValueValidator(10)])
  average = models.DecimalField(decimal_places=1,max_digits=4)
  

  def __str__(self):
    return f'{self.user.username} Votes'
  

  def get_project_ratings(cls, pk):
    ratings = cls.objects.filter(project=pk)
    return ratings
  

  def user_average_rating(self):
    average = (self.design + self.content + self.usability)/3
    return average
  
  def criteria_average(self, pk):
    all_votes = Rating.objects.filter(project=pk)

    usability = []
    design = []
    content = []

    for i in all_votes:
      usability.append(i.usability)
      design.append(i.design)
      content.append(i.content) 

    if len(usability) > 0 or len(design)>0 or len(content)>0:
      average_usability = round(sum(usability)/len(usability),1) 
      average_design = round(sum(design)/len(design),1)
      average_content = round(sum(content)/len(content),1) 
    
    else:
      average_content=0.0
      average_design=0.0
      average_usability=0.0
      average_rating = 0.0

    return {
      'usability':average_usability,
      'design':average_design,
      'content':average_content,
    }
  
  


    



  




  

users/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from PIL import Image

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  prof_pic = CloudinaryField('image')
  bio = models.TextField(max_length=250, blank=True)
  created_at = models.DateField(auto_now_add=True)
  update_at = models.DateField(auto_now=True)

  def __str__(self):
    return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField(max_length=250)

  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['prof_pic', 'bio']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .serializers import ProfileSerializer
from projects.permissions import IsAdminorReadOnly
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

# authentication
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


# models
from django.contrib.auth.models import User
from .models import Profile


def register(request):
  if request.method == 'POST':
    # we create a form that has the request.post data
    form = UserRegisterForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      messages.success(request, f'Account created for { username}')
      return redirect('login')

  else:
    form = UserRegisterForm()
  return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
  if request.method == 'POST':
    u_form = UserUpdateForm(request.POST, instance=request.user)
    p_form = ProfileUpdateForm(request.POST,
                                request.FILES,
                                instance=request.user.profile)
    if u_form.is_valid() and p_form.is_valid():
      u_form.save()
      p_form.save()
      messages.success(request, f'Your account has been updated!')
      return redirect('profile')

  else:
    u_form = UserUpdateForm(instance=request.user)
    p_form = ProfileUpdateForm(instance=request.user.profile)

  context = {
    'u_form': u_form,
    'p_form': p_form
  }

  return render(request, 'users/profile.html', context)




class ProfileList(APIView):
    permission_classes = (IsAdminorReadOnly,)

    def get(self, request, format=None):
        all_profile = Profile.objects.all()
        serializers = ProfileSerializer(
            all_profile, many=True, context={'request': request})
        return Response(serializers.data)

    def post(self, request, format=None):
        serializers = ProfileSerializer(data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=status.HTTP_201_CREATED)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

users/templates/users/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  
  {% if title %}
  <title>{{title}}</title>
  {% else %}
  <title>Rate Me!</title>
  {% endif %}

  {% block styles %}
  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/users.css' %}">
  {% endblock %}
</head>

<body>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  {% block content %}

  {% endblock %}


  {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="../../../static/js/main.js"></script>
  {% bootstrap_javascript %}
  {% endblock %}
</body>

</html>

users/templates/users/login.html
{% extends 'users/base.html'%}
{% load bootstrap5 %}
{%  block content %}
<div class="signup-form">
    <h1>Log In</h1>
    <form action="" method="POST">
      {% csrf_token %}   
        {% bootstrap_form form layout='inline' %} 
        <input type="submit" value="Log In" class="signup-btn">
        <div class="sign-option">
          Don't Have an Account? <a class="ml-2" href="{% url 'register'%}"> Sign Up</a>
        </div>
    </form>
  </div>
{% endblock %}

users/templates/users/logout.html
{% extends 'users/base.html'%}
{% load bootstrap5 %}
{%  block content %}
<div class="logout-page">
  <h1>logged out Successfully!</h1>
  <span><small><a href="{% url 'login'%}">Log In</a></small></span>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'projects/base.html'%}
{% load bootstrap5 %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-7 mt-20">
      <div class="media ">
        <img src="{{ user.profile.prof_pic.url }}" alt="{{user.username}}'s profile picture" class="rounded-circle" width="100"height="90">
      </div>
      <div class="media-body mt-3">
        <h2>{{ user.username }}</h2>
        <p>{{ user.email }}</p>
      </div>
      <hr>
      <h6 class="mb-3 mt-3">My Posts</h6>
      {% if user.project_set.all.count > 0 %}
        <div class="my-posts">
          {% for post in user.project_set.all %}
          <a href="{% url 'post-detail' post.id %}"><img src="{{ post.image.url }}" alt="" class="img-rounded mr-2" width="200"height="150"></a>
          {% endfor %}
        </div>
      {% else %}
        <p>You have no posts</p>
      {% endif %}
    </div>
    <div class="col-md-4">

    <div class="profile-update-form">
      <h3>Update Your <span class="text-danger">Profile</span> </h3>
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form u_form layout='inline' %}
        {% bootstrap_form p_form layout='inline' %}
        <input type="submit" value="Update Profile" class="profile-update-btn">
      </form>
    </div>
  </div>
   
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html'%}
{% load bootstrap5 %}
{% block content %}

    <div class="signup-form">
      <h1>Sign UP</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form layout='inline' %}
        <input type="submit" value="Sign Up" class="signup-btn">
      </form>
      <div class="sign-option">
        Have an Account? <a class="ml-2" href="{% url 'login'%}"> Log in</a>
      </div>
    </div>

{% endblock %}