inspire/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views as user_views
from projects import views as project_views
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('', include('users.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('api-token-auth/', obtain_auth_token)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework import routers
from .views import PostListView, PostDetailView, PostCreateView
from . import views

urlpatterns = [
  path('', PostListView.as_view(), name='homepage'), 
  path('inspiration/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
  path('post/new', PostCreateView.as_view(), name='new_post'),
  path('search-results/', views.search, name='post-search'),
  path('api/v1/projects', views.ProjectList.as_view()),
  path('inspiration/rate/<int:pk>/', views.rate_project, name='rate-project'),
  # path('api/v1/projects/<int:pk>/ratings/', views.RatingsList.as_view(), name='rate_post'),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, 
                        document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from .views import ProfileList
 
urlpatterns = [
  path('profile/', views.profile, name='profile'),
  path('git', views.ProfileList.as_view()),
]

projects/models.py
import math
from django.db import models
from PIL import Image
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MaxValueValidator

class Project(models.Model):
  publisher = models.ForeignKey(User, on_delete=models.CASCADE)
  tag = models.CharField(max_length=50, blank=True, null=True)
  title = models.CharField(max_length=100)
  description = models.CharField(max_length=250)
  image = CloudinaryField('image')
  link = models.URLField(max_length=200)
  country = models.CharField(max_length=100)
  created_at = models.DateField(auto_now_add=True)
  updated_at = models.DateField(auto_now=True)

  def __str__(self):
    return self.title

  def save_project(self):
    return self.save()

  @classmethod
  def get_project(cls, pk):
    project = cls.objects.get(id=pk)
    return project

  def get_absolute_url(self):
    return reverse('post-detail', kwargs={'pk': self.pk})


class Rating(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  project = models.ForeignKey(Project, on_delete=models.CASCADE)
  design = models.PositiveIntegerField(default=0,validators=[MaxValueValidator(10)])
  content = models.PositiveIntegerField(default=0,validators=[MaxValueValidator(10)])
  usability = models.PositiveIntegerField(default=0,validators=[MaxValueValidator(10)])
  average = models.DecimalField(decimal_places=1,max_digits=4)
  

  def __str__(self):
    return f'{self.user.username} Votes'
  

  def get_project_ratings(cls, pk):
    ratings = cls.objects.filter(project=pk)
    return ratings
  

  def user_average_rating(self):
    average = (self.design + self.content + self.usability)/3
    return average
  
  def criteria_average(self, pk):
    all_votes = Rating.objects.filter(project=pk)

    usability = []
    design = []
    content = []

    for i in all_votes:
      usability.append(i.usability)
      design.append(i.design)
      content.append(i.content) 

    if len(usability) > 0 or len(design)>0 or len(content)>0:
      average_usability = round(sum(usability)/len(usability),1) 
      average_design = round(sum(design)/len(design),1)
      average_content = round(sum(content)/len(content),1) 
    
    else:
      average_content=0.0
      average_design=0.0
      average_usability=0.0
      average_rating = 0.0

    return {
      'usability':average_usability,
      'design':average_design,
      'content':average_content,
    }
  
  


    



  




  

projects/forms.py
from django import forms
from .models import Project, Rating

class CreateNewForm(forms.ModelForm):
  class Meta:
    model = Project
    fields = ['image', 'title', 'link', 'description','country', 'tag']

class RatingForm(forms.ModelForm):
  class Meta:
    model = Rating
    fields = ['usability', 'design', 'content']

projects/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Q
from rest_framework import status
from .serializers import ProjectSerializer, RatingSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from django.views.generic import ListView, DetailView, CreateView
from .models import Project, Rating
from .forms import CreateNewForm,RatingForm
from .permissions import IsAdminorReadOnly
from django.contrib.auth.mixins import LoginRequiredMixin

class PostListView(ListView):

  model = Project
  template_name = 'projects/main.html' #template convention is <app>/<model>_<viewtype>.html
  context_object_name = 'projects'
  ordering = ['-id']

class PostDetailView(LoginRequiredMixin, DetailView):
  model = Project
  form_class = RatingForm
  template_name = 'projects/post_detail.html'
  context_object_name = 'project'

  def get_context_data(self, **kwargs):
    context = super(PostDetailView, self).get_context_data(**kwargs)
    context['rating'] = Rating.criteria_average(self, pk=self.object.pk)
    print(context)
    return context

class PostCreateView(LoginRequiredMixin, CreateView):
  model = Project
  form_class = CreateNewForm
  template_name = 'projects/new_post.html'

  def form_valid(self, form):
    form.instance.publisher = self.request.user
    return super().form_valid(form)

class ProjectList(APIView):
  
  def get(self, request, format=None):
    all_projects = Project.objects.all()
    serializers = ProjectSerializer(all_projects, many=True)
    return Response(serializers.data)
  
  def post(self, request, format=None):
    serializers = ProjectSerializer(data=request.data)
    if serializers.is_valid():
      serializers.save()
      return Response(serializers.data, status=status.HTTP_201_CREATED)
    return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

  permission_classes = (IsAdminorReadOnly,)

def search(request):
  template = 'projects/search.html'
  query = request.GET.get('q') 
  results = Project.objects.filter( Q(title__icontains=query) | Q(description__icontains=query) | Q(tag__icontains=query))  
  context ={
    'results':results,
    'term':query
  }
  return render(request, template, context)

def rate_project(request, pk):
  project = Project.get_project(pk)
  
  if request.method == 'POST':
    form = RatingForm(request.POST)
    if form.is_valid():
      rating = form.save(commit=False)
      rating.user = request.user
      rating.project = project
      rating.average = rating.user_average_rating()
      rating.save()
      return redirect('post-detail', pk = project.id)
  else:
    form = RatingForm()

  context = {'project':project,'form':form}
  return render(request,'projects/rating.html',context)

  


  
  
  









 

projects/templates/projects/base.html
{% load bootstrap5 %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% if title %}
    <title>{{title}} . RateMe</title>
    {% else %}
    <title>Rate Me!</title>
    {% endif %} {% include 'projects/partials/navbar.html'%} {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    {% endblock %}
  </head>

  <body>
    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %} {% endif %} {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="../../../static/js/main.js"></script>
    {% bootstrap_javascript %}
  </body>
</html>

projects/templates/projects/main.html
{% extends 'projects/base.html'%}
{% load bootstrap5 %}
{% load static %}

{% block content %}
{{block.super}}
<div class="container">
  <h4 class="main-title ml-3">Top Sites</h4>
  <div class="home-imgs">
    {% for project in projects %}
    <div class="card main-card" style="width: 21rem;">
      <div class="card-img-sec">
        <img class="card-img-top img-fluid image" src="{{ project.image.url }}" alt="website">
        <div class="middle">
          <a href="{% url 'post-detail' project.id %}" class="text btn btn-sm btn-outline-info">View</a>
        </div>
      </div>
      <div class="card-body">
        <h5 class="card-title">
            <p>From: {{project.country}}</p>
            <p>{{ project.created_at}}</p>
        </h5>
        <hr>
        <div class="pub-info">
          <img src="{{ project.publisher.profile.prof_pic.url }}" alt="" class="rounded-circle" height="25" width="25">
          <p class="ml-2">By: {{project.publisher}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

projects/templates/projects/new_post.html
{% extends 'projects/base.html'%}
{% load bootstrap5 %}
{%  block content %}
<div class="new-post">
  <h1>Add Post</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    <input type="submit" value="Submit Project" class="newpost-btn">
  </form>
</div>

{% endblock %}

projects/templates/projects/post_detail.html
{% extends 'projects/base.html'%}
{% load bootstrap5 %}

{% block content %}
<div class="container">
  <div class="details">
    <div class="row">
      <div class="col-md-7">
        <img src="{{ project.image.url }}" alt="" width="730" height="420" class="img-fluid detail-img">
        <p><b>Title:</b> {{ project.title}}</p>
        <p><b>Description:</b> {{ project.description }}</p>
        <p><b>Published by:</b> {{ project.publisher }}</p>
        <span><b>Added on:</b> {{ project.created_at  }} </span>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-3">
        <a href="{% url 'rate-project' project.id%}" class="btn btn-sm btn-outline-danger pl-2 mr-5">Rate</a>
        <a href="{{project.link}}" class="btn btn-sm btn-outline-success">Visit Site</a>
        <div class="criteria_average">
          <h6 class="text-center mt-4 text-success"><b>Criteria Average</b></h6>
          <div class="values">
            <p><b>Design</b><br>{{rating.design}}</p>
            <p><b>Usability</b><br>{{rating.usability}}</p>
            <p><b>Content</b><br>{{rating.content}}</p>
          </div>
    
        </div>
      </div>
    </div>

    <hr>
    <div class="rating-section text-center">
      <h1 style="margin-right: 90px;">Votes</h1>
      {% if project.rating_set.all.count > 0 %}
      {% for vote in project.rating_set.all %}
      <ul>
        <li>
          <div class="row">
            <div class="col-md-4">
              <img src="{{ vote.user.profile.prof_pic.url }}" alt="" class="rounded-circle" height="45" width="45">
              <p class="ml-2"><b>{{vote.user}}</b></p>
            </div>
            <div class="col-md-6" style="display: flex; justify-content:center; flex-direction:row;">
              <h6 class="design ml-3 text-success"><b>Design:</b> {{vote.design}}</h6>&nbsp;&nbsp;&nbsp;
              <h6 class="content ml-3 text-success"><b>Content:</b> {{vote.content}}</h6>&nbsp;&nbsp;&nbsp;
              <h6 class="usability ml-3 text-success"><b>Usability:</b> {{vote.usability}}</h6>&nbsp;&nbsp;&nbsp;
              <h6 class="usability ml-3 text-success"><b>Voter Average:</b> {{vote.average}}</h6>
            </div>
          </div>

        </li>
      </ul>
      {% endfor %}
      {% else %}
      <h4 class="mt-4">This post has not been rated yet</h4>
      {% endif %}

    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
{{block.super}}
<script src="../../../static/js/details.js"></script>
{% endblock %}

projects/templates/projects/rating.html
{% extends 'projects/base.html'%}
{% load bootstrap5 %}
{%  block content %}
<div class="new-post">
  <h1>Rate Site</h1>
  <form action="{%url 'rate-project'  project.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    <input type="submit" value="Rate" class="newpost-btn">
  </form>
</div>
{% endblock %}

projects/templates/projects/search.html
{% extends 'projects/base.html'%}

{% block content %}
<div class="container">
  <div class="home-imgs">
    {% if results %}
    <div class="cat-header container-fluid">
      <h1 class="text-center">Search results for {{ term }} </h1>
    </div>
    {% for item in results %}
    <div class="card main-card" style="width: 21rem;">
      <div class="card-img-sec">
        <img class="card-img-top img-fluid image" src="{{ item.image.url }}" alt="website">
        <div class="middle">
          <a href="{% url 'post-detail' item.id %}" class="text btn btn-sm btn-outline-info">View</a>
        </div>
      </div>
      <div class="card-body">
        <h5 class="card-title">
            <p>From: {{item.country}}</p>
            <p>{{ item.created_at}}</p>
        </h5>
        <hr>
        <div class="pub-info">
          <img src="{{ user.profile.prof_pic.url }}" alt="" class="rounded-circle" height="25" width="25">
          <p class="ml-2">By: {{item.publisher}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h4 class="text-center" style="margin-top: 20px;">There are no images related to {{term}}</h4>
    {% endif %}
  </div>
</div>
{% endblock %}